
New-UDPage -Name "Escalation Matrix" -Icon newspaper_o -Content {


   
 New-UDCollapsible -Items {
    
    New-UDCollapsibleItem -Title "zzzzz Team" -Icon arrow_circle_right -Content {
         
        New-UDTable -Title "Spoc Details" -Headers @(" "," ") -Endpoint {
        
        
            @{

            
                "xxxxx" = "xxxxx"

                "yyyyyy" = "yyyyyy"
            
            }.GetEnumerator() | Out-UDTableData -Property @("Name","Value")
        
        
        
        }
        
    }
}
        
        
  New-UDCollapsible -Items {
    
    New-UDCollapsibleItem -Title "xxx Team" -Icon arrow_circle_right -Content {
         
        New-UDTable -Title "Spoc Details" -Headers @(" "," ") -Endpoint {
        
        
            @{

            	"xxxxx" = "xxxxx"

                "yyyyyy" = "yyyyyy"
            
            }.GetEnumerator() | Out-UDTableData -Property @("Name","Value")
        
        
        
        }
        
    }
}
       
        
    New-UDCollapsible -Items {
    
    New-UDCollapsibleItem -Title "yyy Team" -Icon arrow_circle_right -Content {
         
        New-UDTable -Title "Spoc Details" -Headers @(" "," ") -Endpoint {
        
        
            @{

            
               "xxxxx" = "xxxxx"

                "yyyyyy" = "yyyyyy"

                
            
            }.GetEnumerator() | Out-UDTableData -Property @("Name","Value")
        
        
        
        }
        
    }
}

    
    New-UDCollapsible -Items {
    
    New-UDCollapsibleItem -Title "www Team" -Icon arrow_circle_right -Content {
         
        New-UDTable -Title "Spoc Details" -Headers @(" "," ") -Endpoint {
        
        
            @{

            
                "xxxxx" = "xxxxx"

                "yyyyyy" = "yyyyyy"

                
            
            }.GetEnumerator() | Out-UDTableData -Property @("Name","Value")
        
        
        
        }
        
    }
}  


    New-UDCollapsible -Items {
    
    New-UDCollapsibleItem -Title "jjj Team" -Icon arrow_circle_right -Content {
         
        New-UDTable -Title "Spoc Details" -Headers @(" "," ") -Endpoint {
        
        
            @{

            "xxxxx" = "xxxxx"

                "yyyyyy" = "yyyyyy"

                 

                
            
            }.GetEnumerator() | Out-UDTableData -Property @("Name","Value")
        
        
        
        }
        
    }
}  


    New-UDCollapsible -Items {
    
    New-UDCollapsibleItem -Title "ISLAB" -Icon arrow_circle_right -Content {
         
        New-UDTable -Title "Spoc Details" -Headers @(" "," ") -Endpoint {
        
        
            @{

            
               "xxxxx" = "xxxxx"

                "yyyyyy" = "yyyyyy"

                 

                
            
            }.GetEnumerator() | Out-UDTableData -Property @("Name","Value")
        
        
        
        }
        
    }
}  
        
        
  }      
        
        
        
        
    
    
    
    




